name: amparo_coletivo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: "^3.3.0"
  flutter: "^3.31.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.7
  go_router: ^17.0.0
  provider: ^6.1.1
  flutter_riverpod: ^3.0.3
  supabase_flutter: ^2.9.1
  shimmer: ^3.0.0
  skeletonizer: ^2.0.1
  carousel_slider: ^5.1.1
  photo_view: ^0.15.0
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  image: ^4.1.3
  path_provider: ^2.1.1
  image_picker: ^1.2.0
  uuid: ^4.5.0
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
